version: '3'

services:
  traefik:
    image: containous/traefik:experimental-v2.0 
    command: --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hello-world:
    image: adamgolab/hello-world
    environment:
      - PORT=80
      - WORLD=DevDuck
    expose:
      - "80"
    labels:
      - "traefik.http.routers.hello-world.rule=Host(`devduck.ml`)"
